## ANN

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [5]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [50]:
df.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
x= df.iloc[:,3:-1].values
y= df.iloc[:,-1].values

In [17]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

In [18]:
print(y)

[1 0 1 ... 1 1 0]

In [31]:
#Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,1]= le.fit_transform(x[:,1])
x[:,2]= le.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [34]:
# train and test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 78)

In [41]:
print(x_train.shape,x_test.shape)

(7000, 10) (3000, 10)

In [42]:
print(y_train.shape,y_test.shape)

(7000,) (3000,)

In [46]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
ss= StandardScaler()
x_train= ss.fit_transform(x_train)
x_test= ss.fit_transform(x_test)

## Building ANN

In [56]:
# initializing ANN

model = tf.keras.models.Sequential()

In [57]:
# hidden layer 1

model.add(tf.keras.layers.Dense(units=7,activation ="relu"))

In [58]:

model.add(tf.keras.layers.Dense(units=6,activation ="relu"))

In [59]:
model.add(tf.keras.layers.Dense(units=1,activation ="sigmoid"))

# Training the ANN.

In [61]:
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=["accuracy"])

In [62]:
model.fit(x_train,y_train,batch_size =32,epochs=150)

Epoch 1/150
219/219 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7876
Epoch 2/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4665 - accuracy: 0.8006
Epoch 3/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.8094
Epoch 4/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4196 - accuracy: 0.8146
Epoch 5/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4037 - accuracy: 0.8244
Epoch 6/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3893 - accuracy: 0.8380
Epoch 7/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3771 - accuracy: 0.8474
Epoch 8/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3680 - accuracy: 0.8530
Epoch 9/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8554
Epoch 10/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8564
Epoch 11/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8577
Epoch 12/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8611
Epoch 13/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.8610
Epoch 14/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8589
Epoch 15/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8610
Epoch 16/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3464 - accuracy: 0.8609
Epoch 17/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3457 - accuracy: 0.8609
Epoch 18/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8591
Epoch 19/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3449 - accuracy: 0.8609
Epoch 20/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3443 - accuracy: 0.8606
Epoch 21/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3438 - accuracy: 0.8614
Epoch 22/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8604
Epoch 23/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3437 - accuracy: 0.8607
Epoch 24/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3432 - accuracy: 0.8613
Epoch 25/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3428 - accuracy: 0.8629
Epoch 26/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8611
Epoch 27/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8614
Epoch 28/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3425 - accuracy: 0.8626
Epoch 29/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8631
Epoch 30/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8614
Epoch 31/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8616
Epoch 32/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8610
Epoch 33/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8620
Epoch 34/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3417 - accuracy: 0.8623
Epoch 35/150
219/219 [==============================] - 1s 4ms/step - loss: 0.3413 - accuracy: 0.8626
Epoch 36/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3413 - accuracy: 0.8623
Epoch 37/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3412 - accuracy: 0.8620
Epoch 38/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8626
Epoch 39/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3412 - accuracy: 0.8614
Epoch 40/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3409 - accuracy: 0.8617
Epoch 41/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3410 - accuracy: 0.8617
Epoch 42/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3404 - accuracy: 0.8637
Epoch 43/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3408 - accuracy: 0.8629
Epoch 44/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3404 - accuracy: 0.8634
Epoch 45/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3404 - accuracy: 0.8614
Epoch 46/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3403 - accuracy: 0.8623
Epoch 47/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3402 - accuracy: 0.8636
Epoch 48/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8610
Epoch 49/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.8619
Epoch 50/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8617
Epoch 51/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3394 - accuracy: 0.8607
Epoch 52/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8623
Epoch 53/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8620
Epoch 54/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3390 - accuracy: 0.8619
Epoch 55/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.8626
Epoch 56/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3387 - accuracy: 0.8616
Epoch 57/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3382 - accuracy: 0.8619
Epoch 58/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8633
Epoch 59/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3380 - accuracy: 0.8614
Epoch 60/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8619
Epoch 61/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8643
Epoch 62/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8636
Epoch 63/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8624
Epoch 64/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8633
Epoch 65/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8637
Epoch 66/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.8651
Epoch 67/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3360 - accuracy: 0.8630
Epoch 68/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3364 - accuracy: 0.8634
Epoch 69/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3355 - accuracy: 0.8641
Epoch 70/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3353 - accuracy: 0.8647
Epoch 71/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3349 - accuracy: 0.8656
Epoch 72/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.8637
Epoch 73/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8649
Epoch 74/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8634
Epoch 75/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8650
Epoch 76/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8650
Epoch 77/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8659
Epoch 78/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8653
Epoch 79/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8663
Epoch 80/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8650
Epoch 81/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8649
Epoch 82/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3323 - accuracy: 0.8657
Epoch 83/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8643
Epoch 84/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8641
Epoch 85/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8654
Epoch 86/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8657
Epoch 87/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.8654
Epoch 88/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8659
Epoch 89/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8666
Epoch 90/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3298 - accuracy: 0.8663
Epoch 91/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3297 - accuracy: 0.8664
Epoch 92/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3291 - accuracy: 0.8669
Epoch 93/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3290 - accuracy: 0.8651
Epoch 94/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3293 - accuracy: 0.8657
Epoch 95/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3286 - accuracy: 0.8656
Epoch 96/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3284 - accuracy: 0.8666
Epoch 97/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8680
Epoch 98/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3284 - accuracy: 0.8667
Epoch 99/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8676
Epoch 100/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3277 - accuracy: 0.8670
Epoch 101/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3280 - accuracy: 0.8667
Epoch 102/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8677
Epoch 103/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8670
Epoch 104/150
219/219 [==============================] - 0s 1ms/step - loss: 0.3274 - accuracy: 0.8669
Epoch 105/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8676
Epoch 106/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8673
Epoch 107/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8664
Epoch 108/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3270 - accuracy: 0.8669
Epoch 109/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3266 - accuracy: 0.8659
Epoch 110/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8667
Epoch 111/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8660
Epoch 112/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3261 - accuracy: 0.8674
Epoch 113/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8666
Epoch 114/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3257 - accuracy: 0.8681
Epoch 115/150
219/219 [==============================] - 1s 4ms/step - loss: 0.3261 - accuracy: 0.8671
Epoch 116/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3256 - accuracy: 0.8676
Epoch 117/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3256 - accuracy: 0.8686
Epoch 118/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3253 - accuracy: 0.8684
Epoch 119/150
219/219 [==============================] - 1s 4ms/step - loss: 0.3254 - accuracy: 0.8670
Epoch 120/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3254 - accuracy: 0.8693
Epoch 121/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3256 - accuracy: 0.8681
Epoch 122/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3251 - accuracy: 0.8679
Epoch 123/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3252 - accuracy: 0.8674
Epoch 124/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3254 - accuracy: 0.8670
Epoch 125/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3247 - accuracy: 0.8679
Epoch 126/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3250 - accuracy: 0.8677
Epoch 127/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3247 - accuracy: 0.8677
Epoch 128/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3247 - accuracy: 0.8677
Epoch 129/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3249 - accuracy: 0.8679
Epoch 130/150
219/219 [==============================] - 1s 4ms/step - loss: 0.3249 - accuracy: 0.8663
Epoch 131/150
219/219 [==============================] - 1s 3ms/step - loss: 0.3245 - accuracy: 0.8667
Epoch 132/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3243 - accuracy: 0.8691
Epoch 133/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3241 - accuracy: 0.8684
Epoch 134/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3239 - accuracy: 0.8691
Epoch 135/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3242 - accuracy: 0.8679
Epoch 136/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3241 - accuracy: 0.8689
Epoch 137/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3239 - accuracy: 0.8683
Epoch 138/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3237 - accuracy: 0.8673
Epoch 139/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3239 - accuracy: 0.8679
Epoch 140/150
219/219 [==============================] - 1s 2ms/step - loss: 0.3239 - accuracy: 0.8681
Epoch 141/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3235 - accuracy: 0.8684
Epoch 142/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.8671
Epoch 143/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3233 - accuracy: 0.8700
Epoch 144/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3229 - accuracy: 0.8693
Epoch 145/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3233 - accuracy: 0.8684
Epoch 146/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3228 - accuracy: 0.8683
Epoch 147/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3233 - accuracy: 0.8666
Epoch 148/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8704
Epoch 149/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3229 - accuracy: 0.8676
Epoch 150/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8676

# Predicting

In [68]:
model.predict(ss.transform([[0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))> 0.5

1/1 [==============================] - 0s 27ms/step

array([[False]])

In [70]:
# test set result.
y_pred = model.predict(x_test)
prob_y_pred = (y_pred> 0.5)

model_predict = (y_pred,y_test)

94/94 [==============================] - 0s 2ms/step

In [80]:
y_pred

array([[0.21324037],
       [0.01362363],
       [0.03418219],
       ...,
       [0.08867345],
       [0.34789816],
       [0.04023995]], dtype=float32)

In [79]:
y_test

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [1]:
# confusion Matrix


from sklearn.metrics import classification_report
print(classification_report(model_predict))

NameError: name 'model_predict' is not defined

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test,y_pred)
acc= accuracy_score(y_test,y_pred)
print(cm)

ValueError: Classification metrics can't handle a mix of binary and continuous targets